theme: jekyll-theme-minimal

title: [Digital Signal Processing in Radio Astronomy]
description: [An NSF Research Experience for Teachers Program]

markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-readme-index
  - jekyll-relative-links

sass:
  sass_dir: _sass
  style: compressed
